[build]
  command = "python manage.py collectstatic --noinput && echo 'Static files collected'"
  publish = "staticfiles"
[build.environment]
  PYTHON_VERSION = "3.11.9"

[[redirects]]
  from = "/api/*"
  to = "https://{env:MAIN_API_URL}/api/:splat"
  status = 200
  force = true

# Global redirect to handle SPA routing / 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional headers for CORS (Netlify adds automatically for redirects)